insert into tbl_conceptos
values
(
"1","PAGO X DIAS",
"2"	,"NO COBRA REMUN.",	          
"101"	,"BASICA DEL EMPL",	      
"103"	,"ENCARGATURA",	          
"105"	,"ASIGN.FAMILIAR",	      
"106"	,"REFRIGERIO",	          
"107"	,"HORAS EXTRAS",	      
"108"	,"GRATIFICACION",	      
"109"	,"ESCOLARIDAD",	          
"201"	,"REINT. BASICA",	      
"203"	,"REINT.ENCARGAT.",	      
"205"	,"REINT.ASIG.FAM.",	      
"208"	,"REIT.GRAT.DIC98",	      
"209"	,"REIT.GRAT.JUL99",	      
"210"	,"REIT.GRAT.DIC99",	      
"217"	,"AGUINALDOS",	          
"220"	,"COMP.TIEM.SERV.",	      
"221"	,"COMP.VAC.TRUNCA",	      
"222"	,"CRED.DEVENGADOS",	      
"227"	,"H.EXTRA NO ABON",	      
"230"	,"REINTEGRO GRATI",	      
"235"	,"COMP.VACACIONES",	      
"302"	,"F.PENS",	              
"303"	,"SNP",	                  
"305"	,"IPSS-VIDA",	          
"306"	,"ASIG.JUD.",	          
"307"	,"APORTE AL CAFAE",	      
"309"	,"COOP. PRESIDEN.",	      
"311"	,"IMP.5TA CATEGOR",	      
"312"	,"AFRAMCEP",	          
"318"	,"ADELANTO ESCO",	      
"324"	,"DSCTO CAFAE",	          
"325"	,"ADEUDO F.PEN.",	      
"381"	,"APORT.OBLIG.AFP",	      
"383"	,"COM.VAR.AFP",	          
"385"	,"SEGURO AFP",	          
"401"	,"DSCTO POR DEUDA",	      
"402"	,"CAFAE-RIFA",	          
"405"	,"REDIC.CTA ORLC",	      
"406"	,"DSCTO X CAPACIT",	      
"409"	,"DSCTO FOTOCHECK",	      
"410"	,"FONDO SEPELIO",	      
"411"	,"DONACION",	          
"412"	,"AFRAMCEP",	          
"415"	,"DEVOLUCION CTS",	      
"416"	,"DSCTO GRATIFICA",	      
"418"	,"INASIST.TARDANZ",	      
"420"	,"PREST.WIESE",	          
"421"	,"CAP. CAFAE ORLC",	      
"425"	,"DEVOL.DSCTO SNP",	      
"427"	,"ADELANTO CTS",	      
"435"	,"DCTO REFRIGERIO",	      
"440"	,"PERM.PART.",	          
"483"	,"AFP",	                  
"499"	,"** TOPE AFP **",	      
"501"	,"TOTAL INGRESOS",	      
"502"	,"TOTAL EGRESOS",	      
"503"	,"TOTAL NETO",	          
"601"	,"ESSALUD-PATRONO",	      
"602"	,"ESSALUD-EXIPSS",	      
"603"	,"EMP.PREST.SALUD",	      
"604"	,"IMP.SOLIDARIDAD",	      
"699"	,"TOTAL PATRONO");
